### ISSUE TITLE
Retours code

### ISSUE THREAD

**Issue by cecceccu** [CodeMyMusic/Ateliers2023#1]
Dans le fichier exo1.py, ligne 8, il ne faut jamais utiliser de except sans rien à la suite. Il faut, au strict minimum, écrire except Exception, et idéalement renseigner le type spécifique d'exception que l'on souhaite attraper (ici, except ValueError par exemple).

La structure du fichier Ex1.py semble trop complexe, il faudrait simplifier le code pour ne pas avoir à utiliser un dictionnaire ayant comme valeurs des entiers et des listes (ce n'est pas très propre)

Ex2 : même remarque pour le except (l. 8). Pour la fonction afficher (l.21), il ne semble pas cohérent de mettre le booléen bissextile en paramètre, étant donné qu'il s'agit de l'information que l'on recherche. Pour l'algorithme de calcul de l'année bissextile, l'année est bissextile si elle est divisble par 400 ; il faut modifier les if en conséquence.

**Comment by CodeMyMusic** [comment]
Tout a été corrigé. Concernant l'exo 1, il existe sous plusieurs versions. "ex1_sans_dico.py" est la version sans dico, et "ex1corrige.py" est la meilleure version (selon moi).
